-- USE spring_blog_db;
--
-- INSERT INTO pet_details (description, is_sterile, weight_in_ounces) VALUES ('');
--
-- INSERT INTO pet_details (is_sterile, personalityDescription, weight_in_ounces, name)
-- VALUES ('');